title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-loading-lazy
  - jekyll-sitemap
  - jekyll-target-blank

exclude:
  - .git/
  - .github/
  - .gitignore
  - .jekyll-cache/
  - .nvmrc
  - .ruby-version
  - .sass-cache/
  - .stylelintrc.json
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - Makefile
  - node_modules/
  - package.json
  - vendor
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.error
  - yarn.lock
