name: build and deploy artifact to gh-pages branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Cache gems
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Build the site
        env:
          JEKYLL_ENV: production
        run: |
          bundle update --bundler
          bundle config path vendor/bundle
          bundle config --global frozen 1
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
          # cname: example.com
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
